### PR TITLE
Add rewriteOf and transformOf.

### PR DESCRIPTION
**Pull request by quasicomputational**
These are taken verbatim from `Control.Lens.Plated` in lens, commit
206661eb3d502c0430ded9c95b78b5972961dc5c.

I've left the haddocks as they are, mostly because I wasn't sure what to do with the dangling references.

### CODE REVIEW

**Comment by neongreen** [comment]
It looks like `transformOf` and `rewriteOf` are used very little: https://codesearch.aelve.com/haskell/search?query=\b(transformOf|rewriteOf)\b&insensitive=off&space=off&precise=off&sources=on.

What is your usecase? (Scripting? Library? Application? Switching an existing codebase to lens?)

**Comment by quasicomputational** [comment]
I've found that `transformOf` is pretty nice for manipulating ASTs, and I'd like to use it in `dhall-to-cabal`.

**Comment by neongreen** [comment]
Alright then! Will merge and release a new version soon after.

**Comment by quasicomputational** [comment]
Thanks!

**Comment by neongreen** [comment]
Do you have examples for `rewriteOf` and `transformOf` that I could put in the docs? I guess I could do an example with JSON, but it would be better if the example was base-only.

**Comment by quasicomputational** [comment]
Here's a semi-contrived example of using `rewriteOf`'s compositionality for optimisation and separation of concerns:

```haskell
{-# LANGUAGE LambdaCase #-}

module TinyLang where

import Control.Applicative ( (<|>) )
import Control.Lens ( Traversal', rewriteOf )

data Expr
  = Var String
  | Lit Int
  | Add Expr Expr
  deriving
    ( Eq )

subExprs :: Traversal' Expr Expr
subExprs f = \case
  Var name -> pure ( Var name )
  Lit n -> pure ( Lit n )
  Add a b -> Add <$> f a <*> f b

constantFold :: Expr -> Maybe Expr
constantFold ( Add ( Lit a ) ( Lit b ) ) =
  Just ( Lit ( a + b ) )
constantFold _ =
  Nothing

zeroAdditionIdentity :: Expr -> Maybe Expr
zeroAdditionIdentity ( Add ( Lit 0 ) a ) =
  Just a
zeroAdditionIdentity ( Add a ( Lit 0 ) ) =
  Just a
zeroAdditionIdentity _ =
  Nothing

optimise :: Expr -> Expr
optimise = rewriteOf
  subExprs
  ( \ expr -> constantFold expr <|> zeroAdditionIdentity expr )

example =
  optimise ( Add ( Lit 2 ) ( Add ( Lit (-1) ) ( Lit (-1) ) ) )  == Lit 0
```

**Comment by neongreen** [comment]
Released in [microlens-0.4.11](http://hackage.haskell.org/package/microlens-0.4.11).

**Pull request merged**
