### PR TITLE
added At and Ixed instances for Set and IntSet.

### PR DESCRIPTION
**Pull request by wygulmage**
These instances treat a `Set a` as a `Map a ()`.

If possible, import `Control.Monad.guard` and `Data.Maybe.isJust` instead of defining locally.

### CODE REVIEW

**Comment by neongreen** [comment]
Are these your own reimplementations?

It's better to track the `lens` implementations as closely as possible so that I can easily track `lens` development and port their patches when necessary. So if there is no good reason to deviate from `lens` implementations in this case, you should just copy them verbatim.

**Comment by wygulmage** [comment]
I hadn't even checked whether `lens` implements these instances. If it does, I'll use them.

**Comment by neongreen** [comment]
It does. If it did not implement them, I wouldn't allow them in `microlens` – I want `microlens` to remain a strict subset of `lens`.

**Comment by wygulmage** [comment]
Looks like EK's lens implements instances for Set, and also a pile of other data types that could be included in vanilla microlens. Should I update the pull request to bring those over?

**Comment by neongreen** [comment]
Just `Set`/`IntSet`.

I know `lens` has more instances I haven't ported, but at this point I'm not bringing any new functionality to `microlens` without a request from a `microlens` user. Ideally it should be something like "I miss this functionality", and not merely "I can imagine this being useful".

**Comment by wygulmage** [comment]
My use is
```haskell
  do
    myMaplens . at k .= Nothing
    mySetLens . at k .= Nothing
```
to _idiomatically_ clear out a key that may be in both a map and a set. I could just use `%= Set.delete k`, so it's not a big deal.

**Comment by wygulmage** [comment]
EK's lens package also uses `alterF` for Map `at` (depending on the containers version). Should I update that in this PR too?

**Comment by neongreen** [comment]
Yep.

**Comment by wygulmage** [comment]
Done.

**Comment by wygulmage** [comment]
Alright, I squashed the commits. Wasn't sure whether that's required.

**Comment by neongreen** [comment]
Released microlens-ghc-0.4.12, microlens-platform-0.4.1

**Pull request merged**
